server:
  port: 8088

spring:
  application:
    name: px_service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/px_site?useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:654321}
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:root}
      password: ${REDIS_PASSWORD:654321}
